export const API_URL = 'http://localhost:3000/'

export const ROUTE_LOGIN = 'users/verify-user'
export const ROUTE_CREATE_USER = 'users/create-user'
export const ROUTE_GET_USER = 'users/get-user'
export const ROUTE_UPDATE_USER = 'users/update-user'
export const ROUTE_DELETE_USER = 'users/delete-user'
export const ROUTE_UPDATE_CATEGORIES = 'users/update-categories'
export const ROUTE_GET_CATEGORIES = 'users/get-categories'

export const ROUTE_GET_EXPENSES_OF_USER = 'expenses/get-expenses-of-user'
export const ROUTE_UPDATE_EXPENSE_OF_USER = 'expenses/update-expense-of-user'
export const ROUTE_ADD_EXPENSE_OF_USER = 'expenses/add-expense-of-user'
export const ROUTE_DELETE_EXPENSE_OF_USER = 'expenses/delete-expense-of-user'
export const ROUTE_GET_EXPENSES_OF_USER_BY_DATE_RANGE = 'expenses/get-expenses-of-user-daterange'
export const ROUTE_GET_ACCUMULATED_EXPENSES_OF_N_DAYS = 'expenses/get-accumulated-expenses'
export const ROUTE_GET_PREVIOUS_N_MONTHS_EXPENSES = 'expenses/get-expenses-previous-months'
export const ROUTE_GET_PREVIOUS_N_YEARS_EXPENSES = 'expenses/get-expenses-previous-years'
export const ROUTE_GET_PREVIOUS_N_DAYS_EXPENSES = 'expenses/get-expenses-previous-days'
export const ROUTE_GET_CATEGORIES_COUNTS = 'expenses/get-categories-counts'
export const ROUTE_GET_CATEGORIES_SUMS = 'expenses/get-categories-amounts'
export const ROUTE_POST_FREQUENCY_IN_AMOUNT_RANGES = 'expenses/post-expenses-counts-in-ranges'
export const ROUTE_POST_TOP_N_EXPENSES = 'expenses/post-top-n-expenses'